package com.desofs.audit.model;

public enum AuditAction {
    REGISTER,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOCKOUT,
    REFRESH,
    LOGOUT,
    PROJECT_CREATE,
    PROJECT_READ,
    PROJECT_UPDATE,
    PROJECT_DELETE,
    PROJECT_MEMBER_ADD,
    PROJECT_MEMBER_REMOVE,
    ROLE_CHANGE,
    ATTACHMENT_UPLOAD,
    ATTACHMENT_DOWNLOAD,
    ATTACHMENT_DELETE,
    SESSION_TERMINATE,
    UNEXPECTED_ERROR
}