spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/desofs
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: change_this_to_a_long_random_secret_for_dev_purposes_only
  expiration-ms: 900000 # 15 minutes
