package com.desofs.task;

import com.desofs.task.controller.TaskController;
import com.desofs.task.dto.TaskResponse;
import com.desofs.task.model.Task;
import com.desofs.task.model.TaskStatus;
import com.desofs.task.service.TaskService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Integration tests for {@link TaskController} — full Spring context + MockMvc.
 *
 * All five FR endpoints are covered:
 *   FR-10 – POST   /api/projects/{projectId}/tasks
 *   FR-11 – GET    /api/projects/{projectId}/tasks
 *   FR-12 – PUT    /api/projects/{projectId}/tasks/{taskId}
 *   FR-13 – PATCH  /api/projects/{projectId}/tasks/{taskId}/status
 *   FR-14 – DELETE /api/projects/{projectId}/tasks/{taskId}
 *   FR-15 – PATCH  /api/projects/{projectId}/tasks/{taskId}/assignee
 */
@SpringBootTest
@ActiveProfiles("test")
@AutoConfigureMockMvc
@DisplayName("TaskControllerIT")
class TaskControllerIT {

    @Autowired
    private MockMvc mockMvc;

    @MockitoBean
    private TaskService taskService;

    // ── Shared fixtures ──────────────────────────────────────────────────────

    private static final Long PROJECT_ID = 1L;
    private static final UUID TASK_ID    = UUID.fromString("00000000-0000-0000-0000-000000000001");

    /**
     * Builds a minimal {@link TaskResponse} backed by a real {@link Task} entity
     * so that {@link TaskResponse#from(Task)} can be used as the service stub return value.
     */
    private TaskResponse buildResponse(UUID id, Long projectId, String title, TaskStatus status) {
        Task task = new Task();
        task.setProjectId(projectId);
        task.setTitle(title);
        task.setStatus(status);
        task.setCreatedBy(10L);
        task.setUpdatedAt(LocalDateTime.now());
        // Inject the UUID id via reflection (field has no setter — generated by JPA)
        try {
            java.lang.reflect.Field f = Task.class.getDeclaredField("id");
            f.setAccessible(true);
            f.set(task, id);
        } catch (Exception e) {
            throw new RuntimeException("Failed to set task id via reflection", e);
        }
        return TaskResponse.from(task);
    }

    // ════════════════════════════════════════════════════════════════════════
    // FR-10 – POST /api/projects/{projectId}/tasks
    // ════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("FR-10: POST /api/projects/{projectId}/tasks")
    class CreateTask {

        @Test
        @WithMockUser(username = "dev@example.com", roles = {"ADMIN"})
        @DisplayName("201 Created – task successfully created")
        void createTask_returns201() throws Exception {
            TaskResponse response = buildResponse(TASK_ID, PROJECT_ID, "New Task", TaskStatus.TODO);
            when(taskService.createTask(eq(PROJECT_ID), any(), eq("dev@example.com")))
                    .thenReturn(response);

            mockMvc.perform(post("/api/projects/{projectId}/tasks", PROJECT_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"title\":\"New Task\",\"description\":\"Task description\"}"))
                    .andExpect(status().isCreated())
                    .andExpect(jsonPath("$.title").value("New Task"))
                    .andExpect(jsonPath("$.status").value("TODO"))
                    .andExpect(jsonPath("$.projectId").value(PROJECT_ID));
        }

        @Test
        @WithMockUser(username = "dev@example.com", roles = {"ADMIN"})
        @DisplayName("400 Bad Request – blank title rejected by service")
        void createTask_blankTitle_returns400() throws Exception {
            when(taskService.createTask(eq(PROJECT_ID), any(), eq("dev@example.com")))
                    .thenThrow(new IllegalArgumentException("Task title must not be blank"));

            mockMvc.perform(post("/api/projects/{projectId}/tasks", PROJECT_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"title\":\"   \"}"))
                    .andExpect(status().isBadRequest())
                    .andExpect(jsonPath("$.error").value("Task title must not be blank"));
        }

        @Test
        @WithMockUser(username = "dev@example.com", roles = {"ADMIN"})
        @DisplayName("400 Bad Request – project not found")
        void createTask_projectNotFound_returns400() throws Exception {
            when(taskService.createTask(eq(PROJECT_ID), any(), eq("dev@example.com")))
                    .thenThrow(new IllegalArgumentException("Project not found: " + PROJECT_ID));

            mockMvc.perform(post("/api/projects/{projectId}/tasks", PROJECT_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"title\":\"Task\"}"))
                    .andExpect(status().isBadRequest())
                    .andExpect(jsonPath("$.error").value("Project not found: " + PROJECT_ID));
        }

        @Test
        @WithMockUser(username = "manager@example.com", roles = {"MANAGER"})
        @DisplayName("201 Created – MANAGER can also create tasks (FR-10)")
        void createTask_managerRole_returns201() throws Exception {
            TaskResponse response = buildResponse(TASK_ID, PROJECT_ID, "Manager Task", TaskStatus.TODO);
            when(taskService.createTask(eq(PROJECT_ID), any(), eq("manager@example.com")))
                    .thenReturn(response);

            mockMvc.perform(post("/api/projects/{projectId}/tasks", PROJECT_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"title\":\"Manager Task\"}"))
                    .andExpect(status().isCreated())
                    .andExpect(jsonPath("$.title").value("Manager Task"));
        }

        @Test
        @WithMockUser(username = "user@example.com", roles = {"USER"})
        @DisplayName("403 Forbidden – USER role cannot create tasks")
        void createTask_userRoleRejected_returns403() throws Exception {
            mockMvc.perform(post("/api/projects/{projectId}/tasks", PROJECT_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"title\":\"Task\"}"))
                    .andExpect(status().isForbidden());
        }

        @Test
        @DisplayName("403 Forbidden – unauthenticated request")
        void createTask_unauthenticated_returns403() throws Exception {
            mockMvc.perform(post("/api/projects/{projectId}/tasks", PROJECT_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"title\":\"Task\"}"))
                    .andExpect(status().isForbidden());
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // FR-11 – GET /api/projects/{projectId}/tasks
    // ════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("FR-11: GET /api/projects/{projectId}/tasks")
    class ListTasks {

        @Test
        @WithMockUser(username = "dev@example.com")
        @DisplayName("200 OK – returns list of tasks")
        void listTasks_returns200WithTaskList() throws Exception {
            TaskResponse t1 = buildResponse(TASK_ID, PROJECT_ID, "Task Alpha", TaskStatus.TODO);
            TaskResponse t2 = buildResponse(
                    UUID.fromString("00000000-0000-0000-0000-000000000002"),
                    PROJECT_ID, "Task Beta", TaskStatus.IN_PROGRESS);

            when(taskService.listTasksByProject(eq(PROJECT_ID), eq("dev@example.com"))).thenReturn(List.of(t1, t2));

            mockMvc.perform(get("/api/projects/{projectId}/tasks", PROJECT_ID))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$[0].title").value("Task Alpha"))
                    .andExpect(jsonPath("$[0].status").value("TODO"))
                    .andExpect(jsonPath("$[1].title").value("Task Beta"))
                    .andExpect(jsonPath("$[1].status").value("IN_PROGRESS"));
        }

        @Test
        @WithMockUser(username = "dev@example.com")
        @DisplayName("200 OK – returns empty list when project has no tasks")
        void listTasks_emptyProject_returns200EmptyList() throws Exception {
            when(taskService.listTasksByProject(eq(PROJECT_ID), eq("dev@example.com"))).thenReturn(List.of());

            mockMvc.perform(get("/api/projects/{projectId}/tasks", PROJECT_ID))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$").isArray())
                    .andExpect(jsonPath("$").isEmpty());
        }

        @Test
        @WithMockUser(username = "dev@example.com")
        @DisplayName("400 Bad Request – project not found")
        void listTasks_projectNotFound_returns400() throws Exception {
            when(taskService.listTasksByProject(eq(PROJECT_ID), eq("dev@example.com")))
                    .thenThrow(new IllegalArgumentException("Project not found: " + PROJECT_ID));

            mockMvc.perform(get("/api/projects/{projectId}/tasks", PROJECT_ID))
                    .andExpect(status().isBadRequest())
                    .andExpect(jsonPath("$.error").value("Project not found: " + PROJECT_ID));
        }

        @Test
        @DisplayName("403 Forbidden – unauthenticated request")
        void listTasks_unauthenticated_returns403() throws Exception {
            mockMvc.perform(get("/api/projects/{projectId}/tasks", PROJECT_ID))
                    .andExpect(status().isForbidden());
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // FR-12 – PUT /api/projects/{projectId}/tasks/{taskId}
    // ════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("FR-12: PUT /api/projects/{projectId}/tasks/{taskId}")
    class UpdateTask {

        @Test
        @WithMockUser(username = "dev@example.com", roles = {"MANAGER"})
        @DisplayName("200 OK – task title and description updated")
        void updateTask_returns200() throws Exception {
            TaskResponse response = buildResponse(TASK_ID, PROJECT_ID, "Updated Title", TaskStatus.TODO);
            when(taskService.updateTask(eq(PROJECT_ID), eq(TASK_ID), any(), eq("dev@example.com"))).thenReturn(response);

            mockMvc.perform(put("/api/projects/{projectId}/tasks/{taskId}", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"title\":\"Updated Title\",\"description\":\"Updated desc\"}"))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.title").value("Updated Title"))
                    .andExpect(jsonPath("$.projectId").value(PROJECT_ID));
        }

        @Test
        @WithMockUser(username = "dev@example.com", roles = {"MANAGER"})
        @DisplayName("400 Bad Request – task not found")
        void updateTask_taskNotFound_returns400() throws Exception {
            when(taskService.updateTask(eq(PROJECT_ID), eq(TASK_ID), any(), eq("dev@example.com")))
                    .thenThrow(new IllegalArgumentException("Task not found: " + TASK_ID));

            mockMvc.perform(put("/api/projects/{projectId}/tasks/{taskId}", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"title\":\"Updated Title\"}"))
                    .andExpect(status().isBadRequest())
                    .andExpect(jsonPath("$.error").value("Task not found: " + TASK_ID));
        }

        @Test
        @WithMockUser(username = "dev@example.com", roles = {"MANAGER"})
        @DisplayName("400 Bad Request – task does not belong to project")
        void updateTask_wrongProject_returns400() throws Exception {
            when(taskService.updateTask(eq(PROJECT_ID), eq(TASK_ID), any(), eq("dev@example.com")))
                    .thenThrow(new IllegalArgumentException("Task does not belong to project: " + PROJECT_ID));

            mockMvc.perform(put("/api/projects/{projectId}/tasks/{taskId}", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"title\":\"Updated Title\"}"))
                    .andExpect(status().isBadRequest())
                    .andExpect(jsonPath("$.error").value("Task does not belong to project: " + PROJECT_ID));
        }

        @Test
        @WithMockUser(username = "user@example.com", roles = {"USER"})
        @DisplayName("403 Forbidden – USER role cannot update tasks")
        void updateTask_userRoleRejected_returns403() throws Exception {
            mockMvc.perform(put("/api/projects/{projectId}/tasks/{taskId}", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"title\":\"Updated Title\"}"))
                    .andExpect(status().isForbidden());
        }

        @Test
        @DisplayName("403 Forbidden – unauthenticated request")
        void updateTask_unauthenticated_returns403() throws Exception {
            mockMvc.perform(put("/api/projects/{projectId}/tasks/{taskId}", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"title\":\"Updated Title\"}"))
                    .andExpect(status().isForbidden());
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // FR-13 – PATCH /api/projects/{projectId}/tasks/{taskId}/status
    // ════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("FR-13: PATCH /api/projects/{projectId}/tasks/{taskId}/status")
    class ChangeTaskStatus {

        @Test
        @WithMockUser(username = "dev@example.com")
        @DisplayName("200 OK – status advanced from TODO to IN_PROGRESS")
        void changeStatus_todoToInProgress_returns200() throws Exception {
            TaskResponse response = buildResponse(TASK_ID, PROJECT_ID, "My Task", TaskStatus.IN_PROGRESS);
            when(taskService.changeTaskStatus(eq(PROJECT_ID), eq(TASK_ID), any(), eq("dev@example.com")))
                    .thenReturn(response);

            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/status", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"status\":\"IN_PROGRESS\"}"))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.status").value("IN_PROGRESS"));
        }

        @Test
        @WithMockUser(username = "dev@example.com")
        @DisplayName("200 OK – status advanced from IN_PROGRESS to DONE")
        void changeStatus_inProgressToDone_returns200() throws Exception {
            TaskResponse response = buildResponse(TASK_ID, PROJECT_ID, "My Task", TaskStatus.DONE);
            when(taskService.changeTaskStatus(eq(PROJECT_ID), eq(TASK_ID), any(), eq("dev@example.com")))
                    .thenReturn(response);

            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/status", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"status\":\"DONE\"}"))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.status").value("DONE"));
        }

        @Test
        @WithMockUser(username = "dev@example.com")
        @DisplayName("400 Bad Request – invalid status transition")
        void changeStatus_invalidTransition_returns400() throws Exception {
            when(taskService.changeTaskStatus(eq(PROJECT_ID), eq(TASK_ID), any(), eq("dev@example.com")))
                    .thenThrow(new IllegalArgumentException("Invalid status transition: DONE → TODO"));

            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/status", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"status\":\"TODO\"}"))
                    .andExpect(status().isBadRequest())
                    .andExpect(jsonPath("$.error").value("Invalid status transition: DONE → TODO"));
        }

        @Test
        @WithMockUser(username = "dev@example.com")
        @DisplayName("400 Bad Request – task not found")
        void changeStatus_taskNotFound_returns400() throws Exception {
            when(taskService.changeTaskStatus(eq(PROJECT_ID), eq(TASK_ID), any(), eq("dev@example.com")))
                    .thenThrow(new IllegalArgumentException("Task not found: " + TASK_ID));

            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/status", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"status\":\"IN_PROGRESS\"}"))
                    .andExpect(status().isBadRequest())
                    .andExpect(jsonPath("$.error").value("Task not found: " + TASK_ID));
        }

        @Test
        @WithMockUser(username = "member@example.com")
        @DisplayName("403 Forbidden – MEMBER not assigned to the task is denied (FR-13/SR-4)")
        void changeStatus_nonAssignedMember_returns403() throws Exception {
            when(taskService.changeTaskStatus(eq(PROJECT_ID), eq(TASK_ID), any(), eq("member@example.com")))
                    .thenThrow(new AccessDeniedException(
                            "Only the assigned member or a manager/admin may change this task's status"));

            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/status", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"status\":\"IN_PROGRESS\"}"))
                    .andExpect(status().isForbidden());
        }

        @Test
        @DisplayName("403 Forbidden – unauthenticated request")
        void changeStatus_unauthenticated_returns403() throws Exception {
            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/status", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"status\":\"IN_PROGRESS\"}"))
                    .andExpect(status().isForbidden());
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // FR-14 – DELETE /api/projects/{projectId}/tasks/{taskId}
    // ════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("FR-14: DELETE /api/projects/{projectId}/tasks/{taskId}")
    class DeleteTask {

        @Test
        @WithMockUser(username = "manager@example.com", roles = {"MANAGER"})
        @DisplayName("204 No Content – task soft-deleted successfully")
        void deleteTask_returns204() throws Exception {
            doNothing().when(taskService).deleteTask(PROJECT_ID, TASK_ID, "manager@example.com");

            mockMvc.perform(delete("/api/projects/{projectId}/tasks/{taskId}", PROJECT_ID, TASK_ID))
                    .andExpect(status().isNoContent());
        }

        @Test
        @WithMockUser(username = "manager@example.com", roles = {"MANAGER"})
        @DisplayName("400 Bad Request – task not found")
        void deleteTask_taskNotFound_returns400() throws Exception {
            doThrow(new IllegalArgumentException("Task not found: " + TASK_ID))
                    .when(taskService).deleteTask(PROJECT_ID, TASK_ID, "manager@example.com");

            mockMvc.perform(delete("/api/projects/{projectId}/tasks/{taskId}", PROJECT_ID, TASK_ID))
                    .andExpect(status().isBadRequest())
                    .andExpect(jsonPath("$.error").value("Task not found: " + TASK_ID));
        }

        @Test
        @WithMockUser(username = "manager@example.com", roles = {"MANAGER"})
        @DisplayName("400 Bad Request – task does not belong to project")
        void deleteTask_wrongProject_returns400() throws Exception {
            doThrow(new IllegalArgumentException("Task does not belong to project: " + PROJECT_ID))
                    .when(taskService).deleteTask(PROJECT_ID, TASK_ID, "manager@example.com");

            mockMvc.perform(delete("/api/projects/{projectId}/tasks/{taskId}", PROJECT_ID, TASK_ID))
                    .andExpect(status().isBadRequest())
                    .andExpect(jsonPath("$.error").value("Task does not belong to project: " + PROJECT_ID));
        }

        @Test
        @WithMockUser(username = "user@example.com", roles = {"USER"})
        @DisplayName("403 Forbidden – USER role cannot delete tasks (FR-14)")
        void deleteTask_userRoleRejected_returns403() throws Exception {
            mockMvc.perform(delete("/api/projects/{projectId}/tasks/{taskId}", PROJECT_ID, TASK_ID))
                    .andExpect(status().isForbidden());
        }

        @Test
        @DisplayName("403 Forbidden – unauthenticated request")
        void deleteTask_unauthenticated_returns403() throws Exception {
            mockMvc.perform(delete("/api/projects/{projectId}/tasks/{taskId}", PROJECT_ID, TASK_ID))
                    .andExpect(status().isForbidden());
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // FR-15 – PATCH /api/projects/{projectId}/tasks/{taskId}/assignee
    // ════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("FR-15: PATCH /api/projects/{projectId}/tasks/{taskId}/assignee")
    class AssignTask {

        @Test
        @WithMockUser(username = "dev@example.com")
        @DisplayName("200 OK – task assigned to a user")
        void assignTask_returns200() throws Exception {
            TaskResponse response = buildResponse(TASK_ID, PROJECT_ID, "My Task", TaskStatus.TODO);
            when(taskService.assignTask(eq(PROJECT_ID), eq(TASK_ID), any(), eq("dev@example.com")))
                    .thenReturn(response);

            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/assignee", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"assigneeId\":42}"))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.title").value("My Task"))
                    .andExpect(jsonPath("$.projectId").value(PROJECT_ID));
        }

        @Test
        @WithMockUser(username = "dev@example.com")
        @DisplayName("200 OK – task unassigned (null assigneeId)")
        void unassignTask_returns200() throws Exception {
            TaskResponse response = buildResponse(TASK_ID, PROJECT_ID, "My Task", TaskStatus.TODO);
            when(taskService.assignTask(eq(PROJECT_ID), eq(TASK_ID), any(), eq("dev@example.com")))
                    .thenReturn(response);

            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/assignee", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"assigneeId\":null}"))
                    .andExpect(status().isOk());
        }

        @Test
        @WithMockUser(username = "dev@example.com")
        @DisplayName("400 Bad Request – assignee user not found")
        void assignTask_userNotFound_returns400() throws Exception {
            when(taskService.assignTask(eq(PROJECT_ID), eq(TASK_ID), any(), eq("dev@example.com")))
                    .thenThrow(new IllegalArgumentException("User not found: 99"));

            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/assignee", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"assigneeId\":99}"))
                    .andExpect(status().isBadRequest())
                    .andExpect(jsonPath("$.error").value("User not found: 99"));
        }

        @Test
        @WithMockUser(username = "dev@example.com")
        @DisplayName("400 Bad Request – task not found")
        void assignTask_taskNotFound_returns400() throws Exception {
            when(taskService.assignTask(eq(PROJECT_ID), eq(TASK_ID), any(), eq("dev@example.com")))
                    .thenThrow(new IllegalArgumentException("Task not found: " + TASK_ID));

            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/assignee", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"assigneeId\":42}"))
                    .andExpect(status().isBadRequest())
                    .andExpect(jsonPath("$.error").value("Task not found: " + TASK_ID));
        }

        @Test
        @WithMockUser(username = "member@example.com")
        @DisplayName("403 Forbidden – MEMBER assigning to someone else (FR-15/SR-4)")
        void assignTask_memberAssigningOther_returns403() throws Exception {
            when(taskService.assignTask(eq(PROJECT_ID), eq(TASK_ID), any(), eq("member@example.com")))
                    .thenThrow(new AccessDeniedException("Members may only assign themselves to unassigned tasks"));

            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/assignee", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"assigneeId\":99}"))
                    .andExpect(status().isForbidden());
        }

        @Test
        @WithMockUser(username = "member@example.com")
        @DisplayName("403 Forbidden – MEMBER trying to take an already-assigned task (FR-15/SR-4)")
        void assignTask_memberTakingAssignedTask_returns403() throws Exception {
            when(taskService.assignTask(eq(PROJECT_ID), eq(TASK_ID), any(), eq("member@example.com")))
                    .thenThrow(new AccessDeniedException("Task is already assigned; only a manager/admin may reassign it"));

            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/assignee", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"assigneeId\":42}"))
                    .andExpect(status().isForbidden());
        }

        @Test
        @DisplayName("403 Forbidden – unauthenticated request")
        void assignTask_unauthenticated_returns403() throws Exception {
            mockMvc.perform(patch("/api/projects/{projectId}/tasks/{taskId}/assignee", PROJECT_ID, TASK_ID)
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"assigneeId\":42}"))
                    .andExpect(status().isForbidden());
        }
    }
}

